### ISSUE TITLE
Date field-related issue.[Form-build] 

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#120]
1. date format at build page and at frontend showing different
Check here-
build page-
![image](https://user-images.githubusercontent.com/77260614/132644496-098103e2-3372-4d61-9e10-fa5abdf37e1d.png)

Frontend-
![image](https://user-images.githubusercontent.com/77260614/132644568-050115c7-844d-4f18-81da-699c6c8fa1e8.png)

2. At the frontend date field year format accepting value more than four.
check here-
![image](https://user-images.githubusercontent.com/77260614/132645196-9d91845f-284d-4f26-a249-2c2903608f29.png)

3. Max and Min fields also accepting any random value not showing like in format view

**Comment by rohit-metagauss** [comment]
@Jawed05 JS part is completed for this, Please remove extra icon from input.

**Comment by mJawed** [comment]
Removed extra date icon

**Comment by charan-singh05** [comment]
Date format difference still exist. While building the form, its using "yyyy-mm-dd" and after publishing, form is displaying "dd-mm-yyyy"

Also all date input boxes (min date, max date, default date) in properties for Date control still accept any random entries. We can make them read-only, and user should only be allowed to enter date by clicking on calendar icon next to these properties.

**Comment by charan-singh05** [comment]
The help-text shows date in correct format, but after you select date on calendar for any of the fields, it still shows "yyyy-mm-dd" instead of "dd-mm-yyyyy"

Also, when hovering cursor over calendar icon, for selecting the date, it shows "text cursor" instead of selection cursor.

Lastly, click on any of the date fields in left side panel, and you are still allowed to type in anything- text or numbers etc. When user clicks in the field, then also, the calendar should pop-up and user should NOT be allowed to make custom entries from keyboard. Same behavior should be on Publish page. Format on this page for date is dd/mm/yyyy and it should be consistent, with dd-mm-yyyy instead.

On publish page, after selecting date, a "cross" icon appears in the date box, but clicking on it, nothing happens. It should clear selected date. Mouse hover over this icon should change it into selection icon.

**Comment by charan-singh05** [comment]
Issue fix verified.
